// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjbwutcxrffnoinzwpfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqYnd1dGN4cmZmbm9pbnp3cGZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzNDIwMjAsImV4cCI6MjA3NjkxODAyMH0.WKBT3sGwR6NysychLaMTXkWA74Z9UKVFV4-DC5f6Kl0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});