name: Deploy TMT Frontend

on:
  push:
    branches:
      - ec2-docker-ssl

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build \
            -t techmechatorque/tmtfrontend:latest \
            -t techmechatorque/tmtfrontend:${{ github.sha }} \
            --build-arg VITE_API_URL='${{ secrets.VITE_API_URL }}' \
            .

      - name: Push Docker Image
        run: |
          docker push techmechatorque/tmtfrontend:latest
          docker push techmechatorque/tmtfrontend:${{ github.sha }}

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull Latest Image
        run: docker pull techmechatorque/tmtfrontend:latest

      - name: Stop & Remove Old Container
        run: docker rm -f tmtfrontend-container || true

      - name: Run New Container
        run: |
          docker run -d \
            --restart always \
            -p 3000:80 \
            --name tmtfrontend-container \
            techmechatorque/tmtfrontend:latest

      - name: Renew SSL Certificate
        run: sudo certbot renew --nginx --quiet